/**
 * exportManifest.ts — Cognitive Artifact export manifest generator.
 *
 * Spec: COGNITIVE_ARTIFACT.md §4 + §6
 *
 * Phase 1 deliverable: generate manifest.json with:
 *   - polly_export_version: "1.0"
 *   - All layer slots declared (memory present, rest empty)
 *   - Schema versioned from day one — importers check this before reading layers
 *
 * Phase 3 will populate drift, patterns, practices, reasoning, graph layers.
 * Importers must handle present: false gracefully.
 */

export interface LayerMeta {
  present: boolean;
  schema_version: string | null;
  [key: string]: unknown; // layer-specific count fields (entry_count, etc.)
}

export interface ExportManifest {
  polly_export_version: '1.0';
  created_at: string; // ISO 8601
  owner: string;
  gateway_version: string;
  layers: {
    memory: LayerMeta & { entry_count: number };
    oral_history: LayerMeta & { post_mortem_count: number; annual_count: number };
    drift: LayerMeta;
    patterns: LayerMeta;
    practices: LayerMeta;
    reasoning: LayerMeta;
    graph: LayerMeta;
  };
}

export interface ManifestGeneratorOptions {
  owner: string;
  gatewayVersion: string;
  memoryEntryCount: number;
  postMortemCount: number;
  annualCount: number;
}

/**
 * Generate a Phase 1 manifest.json object.
 *
 * All Phase 3 layers are declared but empty (present: false).
 * This ensures Phase 3 importers can parse Phase 1 exports without errors.
 */
export function generateExportManifest(opts: ManifestGeneratorOptions): ExportManifest {
  return {
    polly_export_version: '1.0',
    created_at: new Date().toISOString(),
    owner: opts.owner,
    gateway_version: opts.gatewayVersion,
    layers: {
      memory: {
        present: opts.memoryEntryCount > 0,
        schema_version: '1.0',
        entry_count: opts.memoryEntryCount,
      },
      oral_history: {
        present: opts.postMortemCount > 0 || opts.annualCount > 0,
        schema_version: '1.0',
        post_mortem_count: opts.postMortemCount,
        annual_count: opts.annualCount,
      },
      // Phase 3 layers — declared but empty
      drift: {
        present: false,
        schema_version: null,
      },
      patterns: {
        present: false,
        schema_version: null,
      },
      practices: {
        present: false,
        schema_version: null,
      },
      reasoning: {
        present: false,
        schema_version: null,
      },
      graph: {
        present: false,
        schema_version: null,
      },
    },
  };
}

/**
 * Generate the Archivist README.md content for a Phase 1 export.
 * Minimal but complete — human-readable entry point per spec §5.
 */
export function generateArchivistReadme(
  manifest: ExportManifest,
  exportDate: string
): string {
  const presentLayers = Object.entries(manifest.layers)
    .filter(([, meta]) => meta.present)
    .map(([name]) => name);

  const absentLayers = Object.entries(manifest.layers)
    .filter(([, meta]) => !meta.present)
    .map(([name]) => name);

  return `# Polly Cognitive Artifact Export
*Exported: ${exportDate}*

## Owner
${manifest.owner}

## What's Here
This export was generated by Polly (gateway v${manifest.gateway_version}) and contains the following layers:

${presentLayers.map((l) => `- **${l}** — present and populated`).join('\n')}

## What's Not Here
The following layers are declared in the manifest but not yet populated (Phase 3 features):

${absentLayers.map((l) => `- **${l}**`).join('\n')}

## How to Read This Export
- Start with \`manifest.json\` for machine-readable structure
- \`memory/\` contains daily memory files — chronological record of Polly sessions
- Oral history (\`oral_history/\`) will contain post-mortems and annual syntheses when generated

## Importing into a New Polly Instance
Use Polly's import flow (Settings → Import Cognitive Artifact) to load this export.
The new instance will receive structural orientation — not raw memory, but the shape of prior work.

## Format Version
This export uses \`polly_export_version: "1.0"\`. Future Polly versions are backward-compatible with this format.
`;
}
